### ISSUE TITLE
Incorrect use or defintion of publish() method in PubSubSystem class

### ISSUE THREAD

**Issue by shubug** [ashishps1/awesome-low-level-design#14]
Context: pubsubsystem

publish() method of PubSubSystem class is not getting used anywhere. From PubSubDemo file, we can see Publishers are directly calling the publish method of Topic, bypassing the PubSubSystem layer.

The entire implementation of PubSubSystem class has no mention of Publisher class, and directly dealing with Topic class and it's methods. This seems to break the OOPs concept.

**Comment by ashishps1** [comment]
Hey, thanks for pointing out.
PubSubSystem class was actually redundant so I have removed it.

Let me know if you see any other concern.
