### ISSUE TITLE
Permission to add solutions in golang

### ISSUE THREAD

**Issue by mukulagarwal08** [ashishps1/awesome-low-level-design#29]
Hey was trying to push to a branch but got access denied to push to repo! Have started with parking lot

**Comment by mukulagarwal08** [comment]
@ashishps1 Hey can I get the permission to push to this repo?

**Comment by ashishps1** [comment]
Hey, could you create a pull request instead after forking this repository and making the changes?

**Comment by mukulagarwal08** [comment]
okay cool!
