### ISSUE TITLE
Design Pattern in JS

### ISSUE THREAD

**Issue by PrasanthVijayy** [ashishps1/awesome-low-level-design#48]
Hi @ashishps1!

I’m interested in contributing to your repository, especially focusing on `design patterns in JS.`

Could you let me know how I can get involved?

Thanks in advance!

**Comment by PrasanthVijayy** [comment]
@ashishps1!

Waiting for you're reply.

**Comment by ashishps1** [comment]
@PrasanthVijayy , you are welcome to contribute.

You can add your changes inside the design-patterns directory and then open a pull request.

**Comment by PrasanthVijayy** [comment]
Sure, thank you!
